### ISSUE TITLE
Allow transparent for values above/below the specified color range

### ISSUE THREAD

**Issue by rsignell-usgs** [Unidata/ncWMS#10]
What should we do with values that are outside the specified color range?  

NcWMS sets them to black:
![5-6-2015 3-49-31 pm](https://cloud.githubusercontent.com/assets/1872600/7502547/c387d89c-f40a-11e4-8fbe-d1c21ffc61b5.png)

But as the above image illustrates, black is not always what is most useful for the user. 

In many cases, transparent would be more valuable.   This would allow land and bathymetry to "show through" in the range of colors that are not of interest to the user. So I would argue that transparent would be a better choice than black.    

Ideally the user/client could specify the behavior, but this would require adding yet another non-standard WMS parameter.

**Comment by ggalibert** [comment]
I think _FillValue is transparent while a value lower or equal (?) to the lowest color range is black.

You should try to set _FillValues where the land is and you should be able to see through.

**Comment by rsignell-usgs** [comment]
@ggalibert , the problem is that in this model, the elevation field does not have a constant value over land, and thus a  `_FillValue` cannot be assigned.  

I guess it hard to argue that transparent outside the range would always be preferred to the black.    But it certainly would come in handy in many situations, so I guess we could add it as another option on the WMS request.   

What do folks think about that?
-Rich

**Comment by JonDHo** [comment]
This issue is a bit old and perhaps I have misunderstood, but isn't this what the existing ABOVEMAXCOLOR and BELOWMINCOLOR parameters specifically allow - we set them to 'transparent' to achieve exactly what you are talking about. The GoDiva tool doesn't implement UI components for them but they are there already in ncWMS.

**Comment by rsignell-usgs** [comment]
@JonDHo, yes, at this time I did not know about all the WMSExtentions at:
http://www.resc.rdg.ac.uk/trac/ncWMS/wiki/WmsExtensions

And yes, Godiva2 or other WMS clients could use those to implement the behavior I was looking for.
So closing this issue...
