### ISSUE TITLE
Update prototype.js from (2009) ver. 1.6.1

### ISSUE THREAD

**Issue by ghkostov** [Unidata/ncWMS#17]
It looks like prototype.js is pulled by ncWMS (the Godiva2 client) and is at a rather old (2009) version 1.6.1.  The current one is 1.7.3. 
No particular vulnerability that we know of, but a recommendation from best practices guide to stay with latest releases.
Thanks!
P.S. Is it still being used, or is it just an artifact from an older time?

**Comment by ghkostov** [comment]
Folks, any chance this will be getting updated in an upcoming release?
Thanks!

**Comment by lesserwhirls** [comment]
Greetings @ghkostov - I just made a PR addressing this. My initial testing indicates that it was a seamless update to the library, but it will be good to get others input if there is any feedback.
