### ISSUE TITLE
Integrate ncWMS2.1+ into THREDDS

### ISSUE THREAD

**Issue by rsignell-usgs** [Unidata/ncWMS#19]
@lesserwhirls , @ethanrd, @cwardgar :  Oh Man!  The Reading guys now have ncWMS2 working with unstructured grids!   See:
https://github.com/Reading-eScience-Centre/edal-java/issues/44#issuecomment-192283106

Could we prioritize this for inclusion into the TDS?

It would be *so* useful for the community.

**Comment by ktyle** [comment]
+1

Sent from my iPhone

On Mar 4, 2016, at 8:46 AM, Rich Signell <notifications@github.com<mailto:notifications@github.com>> wrote:


@lesserwhirls<https://github.com/lesserwhirls> , @ethanrd<https://github.com/ethanrd>, @cwardgar<https://github.com/cwardgar> : Oh Man! The Reading guys now have ncWMS2 working with unstructured grids! See:
Reading-eScience-Centre/edal-java#44 (comment)<https://github.com/Reading-eScience-Centre/edal-java/issues/44#issuecomment-192283106>

Could we prioritize this for inclusion into the TDS?

It would be so useful for the community.

-

**Comment by ocefpaf** [comment]
> The Reading guys now have ncWMS2 working with unstructured grids!

That would be an awesome addition to THREDDS!

**Comment by rsignell-usgs** [comment]
Just to add a few pretty UGRID ncWMS2 pictures here:
Surface current from FVCOM:
![2016-03-04_8-24-04](https://cloud.githubusercontent.com/assets/1872600/13530738/e6a26250-e1f0-11e5-8826-ad32cfebbc74.png)
Bottom temperature from FVCOM:
![2016-03-04_8-19-56](https://cloud.githubusercontent.com/assets/1872600/13530739/eaa02e78-e1f0-11e5-8214-2c62d164d244.png)
Water levels from ADCIRC:
![2016-03-03_21-27-17](https://cloud.githubusercontent.com/assets/1872600/13530764/0517f7a4-e1f1-11e5-838c-19ab0622f4d5.png)

**Comment by kwilcox** [comment]
plus one million

**Comment by jgallagher59701** [comment]
+1

Woo hoo

Hey, there are issue with the Godiva interface and https - can we work on those?

**Comment by guygriffiths** [comment]
@jgallagher59701 - What issues are you having with Godiva and https?  If it's easily summarisable, could you post an issue on our issue tracker?
https://github.com/Reading-eScience-Centre/edal-java/issues

**Comment by lesserwhirls** [comment]
Hi all, totally agree! The new ncwms (edal-java) stuff is way different than the current version the TDS (4.x) uses. As such, it required some work to get into TDS 5.0, but it's working. Many thanks to @guygriffiths for the help! Here is the pull request to the THREDDS project that makes the magic happen (note we are using edal 1.1.1, which I think translates to 2.1.1, so it should have the ugrid stuff in it):

Unidata/thredds#343

**Comment by dharhas** [comment]
+1

**Comment by ChrisBarker-NOAA** [comment]
very cool +1

**Comment by dpsnowden** [comment]
Very cool.  Just left a pitch for SGRID too at [edal-java/#46](https://github.com/Reading-eScience-Centre/edal-java/issues/46) .  Any chance that's on the development roadmap soon?

**Comment by thomaspeacock72** [comment]
useful +1

**Comment by rsignell-usgs** [comment]
This issue now lives here
https://github.com/Unidata/thredds/issues/618
so closing this one.
