### ISSUE TITLE
incorrect link to OGC

### ISSUE THREAD

**Issue by Ram-Sys** [Unidata/ncWMS#32]
TDS_VERSION 4.6.16.1
Thredds-Docker on Linux

Just kind of a typo: On the page with Godiva Viewer in the attribution "Powered by OpenLayers and OGC standards" the second link is also directing to OpenLayers and not to OGC.

Should be maybe changed to https://www.ogc.org/

(Thank you very much for providing Thredds Server!)

**Comment by lesserwhirls** [comment]
Thank you for the report! We'll get this addressed in the next release.
